Repository 3kh0/3kh0.github.io, pull requests merged in 2022-02, with the labels that each got.

#22 Mobile Improvements by @littlepriceonu
  css/style.css
  index.html
  js/main.js
Labels: enhancement

#46 fixed an image alt tag
  index.html
Labels: ✨ Enhancement

#50 Fixing the TMS system
  404.html
  index.html
  js/lib.js
  js/tms.js
Labels: 🐜 Bug, ✨ Enhancement
