Repository 3kh0/3kh0.github.io, pull requests merged in 2022-11, with the labels that each got.

#237 Bump node
  server/package-lock.json
  server/package.json
Labels: dependencies

#244 Make styles work on forks
  projects.html
Labels: ✨ Enhancement

#249 Apply fixes from CodeFactor
  projects/stickman-golf/media/font/FredokaOne-Regular.ttf.html
Labels: ✨ Enhancement

#258 Apply fixes from CodeFactor
  projects/happy-hop/c2runtime.js
Labels: ✨ Enhancement

#279 more easily add roms to projects/webretro
  projects/webretro/roms.html
  projects/webretro/roms.json
Labels: ✨ Enhancement

#281 Revert "more easily add roms to projects/webretro"
  projects/webretro/roms.html
  projects/webretro/roms.json
Labels: ✨ Enhancement

#290 Add pop cat classic
  dump/changelog.txt
  index.html
  projects.html
  projects/popcat-classic/CNAME
  projects/popcat-classic/LICENSE
  projects/popcat-classic/README.md
  projects/popcat-classic/android-chrome-192x192.png
  projects/popcat-classic/android-chrome-512x512.png
  projects/popcat-classic/apple-touch-icon.png
  projects/popcat-classic/browserconfig.xml
  projects/popcat-classic/favicon-16x16.png
  projects/popcat-classic/favicon-32x32.png
  projects/popcat-classic/favicon.ico
  projects/popcat-classic/imgs/bg.jpg
  projects/popcat-classic/imgs/og-card.jpg
  projects/popcat-classic/imgs/op.png
  projects/popcat-classic/imgs/p.png
  projects/popcat-classic/imgs/popcat.svg
  projects/popcat-classic/imgs/twitter-card.jpg
  projects/popcat-classic/index.html
  projects/popcat-classic/mstile-150x150.png
  projects/popcat-classic/pops/pop1.mp3
  projects/popcat-classic/pops/pop2.mp3
  projects/popcat-classic/pops/pop3.mp3
  projects/popcat-classic/pops/pop4.mp3
  projects/popcat-classic/safari-pinned-tab.svg
  projects/popcat-classic/site.webmanifest
  projects/popcat-classic/splash.png
Labels: ✨ Enhancement

#291 Apply fixes from CodeFactor
  projects/popcat-classic/index.html
Labels: ✨ Enhancement

#293 Add 1v1.lol
  dump/changelog.txt
  index.html
  projects.html
  projects/1v1lol/UnityLoader.js
  projects/1v1lol/css/style.css
  projects/1v1lol/favicon.png
  projects/1v1lol/firebase/firebase-analytics.js
  projects/1v1lol/firebase/firebase-app.js
  projects/1v1lol/firebase/firebase-auth.js
  projects/1v1lol/firebase/firebase-firestore.js
  projects/1v1lol/firebase/firebase-remote-config.js
  projects/1v1lol/index.html
  projects/1v1lol/js/IronSourceRV.js
  projects/1v1lol/js/adblockManager.js
  projects/1v1lol/js/cpmstar.js
  projects/1v1lol/js/firebase-config.js
  projects/1v1lol/js/firebase.js
  projects/1v1lol/js/fullscreen.js
  projects/1v1lol/js/login.js
  projects/1v1lol/js/macUserAgent.js
  projects/1v1lol/js/mobileRedirect.js
  projects/1v1lol/js/sdkloader/ima3.js
  projects/1v1lol/js/visibilityChangeListener.js
  projects/1v1lol/js/windowResize.js
  projects/1v1lol/lib/jquery.min.js
  projects/1v1lol/logo.png
  projects/1v1lol/splash.png
  projects/1v1lol/webcopy-origin.txt
Labels: ✨ Enhancement

#299 Add some silly subtitles.
  js/subtitle.js
Labels: ✨ Enhancement

#302 Update changelog for #283
  dump/changelog.txt
Labels: ✨ Enhancement

#307 Allow styles on forks to work
  index.html
Labels: ✨ Enhancement

#327 Fix Redirects on 1v1.lol mobile
  dump/changelog.txt
  projects/1v1lol/js/mobileRedirect.js
Labels: 🐜 Bug, ✨ Enhancement

#348 auto update everyone's fork
  .github/workflows/fork-sync.yml
  dump/changelog.txt
Labels: ✨ Enhancement

#356 Fix Fake Virus Redirect
  projects.html
Labels: ✨ Enhancement

#381 added wall smash from wallsmash.com
  projects.html
  projects/wallsmash/bundle.804bae11.js
  projects/wallsmash/index.html
  projects/wallsmash/thumb.png
Labels: ✨ Enhancement
